
export const quickQuestions = [
  'How does it work?',
  'Is it accurate?',
  'What factors do you consider?',
  'How can I improve my lifespan?',
  'Is my data safe?',
  'What about diet?',
  'How important is exercise?',
  'How does stress affect health?',
  'Why is sleep important?',
  'Should I quit smoking?',
  'How much water should I drink?',
  'Are social connections important?',
  'What about mental health?',
  'How often should I get checkups?',
  'What about heart health?',
  'How to keep brain healthy?',
  'Tips for healthy aging?',
  'Do I need vitamins?',
  'Benefits of meditation?',
  'Cancer prevention tips?',
  'How to prevent diabetes?',
  'What about bone health?',
  'How to boost immune system?',
  'Longevity secrets?',
  'Best foods for health?',
  'How to increase energy?',
  'Weight management tips?',
  'Genetics vs lifestyle?'
];
